version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '5000:5000'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
